baby_ball:
  name: "&6Baby Ball"
  lore:
    - "&fIt's nice to be a baby"
    - ""
    - "&dCreated by joe_the_mc_player as part of the"
    - "&dAugust 2016 player head contest."
  uuid: 37a578d2-b464-40b6-9328-7a76cd60d98a
  value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjFiNjNmNmMzZmVkNGU3ZmMxNjg1OGE0NTk3Y2RhNTdhZjUxYmIzN2UyODU5NjkxNDU3NDg3ZmM4ZDIifX19
red_apple:
  name: "Apple"
  lore:
    - "A tasty apple."
  uuid: 0d5fd9c3-d044-478f-b774-d37b5f86fa2a
  value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTJiMzViZGE1ZWJkZjEzNWY0ZTcxY2U0OTcyNmZiZWM1NzM5ZjBhZGVkZjAxYzUxOWUyYWVhN2Y1MTk1MWVhMiJ9fX0=
orange:
  name: "Orange"
  lore:
    - "Orange citrus"
  uuid: 1b9b28c5-9d06-4b69-934c-515b29f2e632
  value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjViMWRiNTQ3ZDFiNzk1NmQ0NTExYWNjYjE1MzNlMjE3NTZkN2NiYzM4ZWI2NDM1NWEyNjI2NDEyMjEyIn19fQ==
coca_cola:
  name: "Cola"
  lore:
    - "A refreshing cola."
  uuid: 8a145e5e-957d-418c-b000-511c971ae698
  value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTNiMDFmYjJmNmJhNDdjOWQ3NjM4NDkxZjM3Y2Q4NTgyYTkzNzczMTE4NmRmNGQxZWNjZDU5YjY1YmYzNyJ9fX0=
ham_cheese_sandwich:
  name: "Ham and Cheese Sandwich"
  lore:
    - "Pig infused"
  uuid: 0e773357-dd3b-4d3e-bd93-6b179dc43a44
  value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGEyMTJmNzBmYjY2NTQ4ZmRmMmFiY2RiY2U4ZjMxNzA0MzRiODk5NWUyMWQxNGY5YjFmZjE0OTdjNjQ4ZCJ9fX0=
  